server:
  port: 8080
  session:
    timeout: 20000
    store-dir: jdbc

spring:
    datasource:
        name: test

        url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

    mvc:
      static-path-pattern: /static/**


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.springboot.tongyuyan.selfhelp.winter.model

#pagehelper  ҳ
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
pay:
  url:  "https://api.mch.weixin.qq.com/pay/unifiedorder"
  random: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"
  API_KEY: "***"
  MCH_ID: "**"
  APP_ID: "****"

apliy:
  app_private_key: "***"
  public_key: "***"
#静态资源


# JWT 认证配置
jwt:
  header: Authorization
  secret: w-oasis123456
  expiration: 604800 #token七天不过期
  tokenHead: "Bearer "
  exceptUrl: "/auth/**"

